import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'brava',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <Script src='https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js' />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
